### ISSUE TITLE
Support dynamic tags in the Dockerfile FROM

### ISSUE THREAD

**Issue by shenxianpeng** [shenxianpeng/cpp-linter-action#12]
By default, in the GitHub Action `yml`, clang-tools version is used the latest version, but supports the user-specific clang-tools version. 

More conversion see this ticket: https://github.com/shenxianpeng/clang-tools/issues/1

**Comment by 2bndy5** [comment]
I'm starting to think that parsing the diff for files can actually be done with bash script (using a combination of `grep`, `tr`, & `sep` commands).

Latest dilemma is parsing a files diff that's split into "hunks". For example, this commits diff
![image](https://user-images.githubusercontent.com/14963867/130322460-f5ef412e-b366-4528-88e5-fa0c31514835.png)

looks like this in the JSON payload
```json
[{
  "files": [{
    "patch": "@@ -32,7 +32,7 @@ args=(\"$@\")\n FMT_STYLE=${args[0]}\n IFS=',' read -r -a FILE_EXT_LIST <<< \"${args[1]}\"\n TIDY_CHECKS=\"${args[2]}\"\n-# CLANG_VERSION=\"${args[3]}\"\n+CLANG_VERSION=\"${args[3]}\"\n \n echo \"GH_EVENT_PATH = $GITHUB_EVENT_PATH\"\n echo \"processing $GITHUB_EVENT_NAME event\"\n@@ -128,8 +128,8 @@ do\n       CLANG_CONFIG=\"--config\"\n    fi\n \n-   clang-tidy \"$filename\" \"$CLANG_CONFIG\" >> clang_tidy_report.txt\n-   clang-format -style=\"$FMT_STYLE\" --dry-run \"$filename\" >> clang_format_report.txt\n+   clang-tidy-\"$CLANG_VERSION\" \"$filename\" \"$CLANG_CONFIG\" >> clang_tidy_report.txt\n+   clang-format-\"$CLANG_VERSION\" -style=\"$FMT_STYLE\" --dry-run \"$filename\" >> clang_format_report.txt\n \n    echo \"Current Working Directory = $CWD\"\n    if [[ $(wc -l < clang_tidy_report.txt) -gt 0 ]]"
  }]
}]
```

**Comment by shenxianpeng** [comment]
This has been supported through the input name `version`.
