### ISSUE TITLE
Update README to release v1.2.0

### ISSUE THREAD

**Issue by shenxianpeng** [shenxianpeng/cpp-linter-action#15]
## 🚀New Features
- Support optional Inputs `style`, `extensions`, `tidy-checks`,  `repo-root`, `version`
  - #4 PR  by @2bndy5 
- Add compatibility for push events
  - #8 by @2bndy5 
  - #6 by @2bndy5 
- Support intuitive action exit code
  - #7 by @2bndy5 
- Support versions of clang-format and clang-tidy
  - https://github.com/shenxianpeng/clang-tools/issues/1 by @2bndy5 @shenxianpeng 
### 🚨 Removed 
- Removed Cppcheck
  - #2 by @shenxianpeng

**Comment by 2bndy5** [comment]
I was just going to update the README about the demo picture and make the table a little more readable.

**Comment by shenxianpeng** [comment]
Yes, it has a duplicate paragraph and the demo sections need also updated.

**Comment by 2bndy5** [comment]
Before you make a new release it may be prudent to delete any previously posted comments (made by the bot) when posting new comments to the same thread.
