### ISSUE TITLE
cpp-linter-action app can not visit 

### ISSUE THREAD

**Issue by shenxianpeng** [shenxianpeng/cpp-linter-action#18]
Can't visit this app's link https://github.com/marketplace/actions/c-c-lint-action

And also can not find the app in the marketplace. 

![image](https://user-images.githubusercontent.com/3353385/130379598-9be7bf0c-df74-4109-b7e1-f65b48f4c0aa.png)

I just see a prompt to let me release again, maybe it cause by last night I modify the release note.

**Comment by 2bndy5** [comment]
strange, it doesn't seem to be on the marketplace anymore (it was yesterday after the latest release.

The [GH docs about publishing an action](https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace) do mandate some stipulations; maybe we violated 1 of them by renaming the action...

**Comment by shenxianpeng** [comment]
![image](https://user-images.githubusercontent.com/3353385/130381367-beed94d6-0219-4d78-a189-215f8dfcc972.png)
I need to change the description back.

**Comment by 2bndy5** [comment]
that's strange I count 122 characters in the description. Maybe the `&` is being viewed differently under the hood

**Comment by shenxianpeng** [comment]
![image](https://user-images.githubusercontent.com/3353385/130381673-4518a986-f84e-45e6-8304-4f712503803e.png)

It looks good now ...

**Comment by shenxianpeng** [comment]
I will try to post release to version 1.2.1

**Comment by shenxianpeng** [comment]
Done. the app back to the marketplace: https://github.com/marketplace/actions/c-c-lint-action

**Comment by shenxianpeng** [comment]
It can not be visited again...

**Comment by 2bndy5** [comment]
maybe it needs some time to show up?

**Comment by shenxianpeng** [comment]
> Done. the app back to the marketplace: https://github.com/marketplace/actions/c-c-lint-action

This link can be visited after publish, but after a few dozen seconds, it can not be visited again. very strange

**Comment by 2bndy5** [comment]
I think this may require help form GH support. 
- [Try asking the community](https://github.community/)
- [go to GH support directly](https://support.github.com/contact)

**Comment by shenxianpeng** [comment]
It can be visited again https://github.com/marketplace/actions/c-c-lint-action after I editing the release
