### ISSUE TITLE
Ideas from other apps

### ISSUE THREAD

**Issue by shenxianpeng** [shenxianpeng/cpp-linter-action#20]
Links of some other apps

* https://probot.github.io/apps/
* https://github.com/sdras/awesome-actions

Maybe we can go to these places for promotion someday.

**Comment by shenxianpeng** [comment]
Notes: get ideas about README, Logo, etc from these quality apps.

* https://github.com/wemake-services/wemake-python-styleguide
* https://github.com/reviewdog
* https://github.com/marketplace/actions/dotenv-linter
* https://github.com/marketplace/actions/lint-action
* https://github.com/marketplace/actions/markdown-linting-action
* https://github.com/xt0rted/stylelint-problem-matcher
* https://github.com/sonarsource/sonarcloud-github-action

**Comment by shenxianpeng** [comment]
project log 😃 
![cpp lint logo](https://user-images.githubusercontent.com/3353385/130488390-b31d099e-b91f-460a-a48d-84483d5320e0.png)

**Comment by shenxianpeng** [comment]
![image](https://user-images.githubusercontent.com/3353385/130489613-c93dfb06-5595-49dc-8272-2b620196edf8.png)

**Comment by 2bndy5** [comment]
I've been trying to find out how to make it own bot. This also helps branding the action, but may actually be useful with find not comments made by this action (not other actions).

**Comment by shenxianpeng** [comment]
It really cool to have our own bot and looks more professional to others. 
Nice, I will post a larger logo and checkmark of the first one later.

**Comment by shenxianpeng** [comment]
This is the largest size obtained from free which is 200*200

![logo_200x200](https://user-images.githubusercontent.com/3353385/130636015-a77df46e-07b7-477d-ad4e-7e7d87231ddf.png)
![checkmark_200x200 ](https://user-images.githubusercontent.com/3353385/130636032-3f496fb8-21ae-43ec-a135-83f543a952ae.png)
