### ISSUE TITLE
open to contributions?

### ISSUE THREAD

**Issue by 2bndy5** [shenxianpeng/cpp-linter-action#3]
I'm glad to see someone taking up the torch to update ArtificialAmateur's stale action. I was wondering if you'd be open to contributions. I'd like to add an input option that makes use of clang-format's `--style=` arg. Also, I think there's a way to consolidate the demo repo into this one.

**Comment by shenxianpeng** [comment]
I'm very glad you would like to contribute, and support `--style=` option will be very helpful, please go ahead.
About consolidate the demo repo into this one, could explain more? Thank you!

**Comment by 2bndy5** [comment]
> About consolidate the demo repo into this one, could explain more? 

I'm just guessing here, but you could have a "demo" subdirectory in this repo that exists on 2 branches. 1 branch would have a PR open to merge un-formatted code to the other branch. Let the this action run on this repo as you would for any other repo (except pinned to the this repo's master branch instead of a version like `shenxianpeng/cpp-linter-action@master`), so the PR would demonstrate the bot comments.

**Comment by shenxianpeng** [comment]
I think I get your point. I will try to do so, thanks very much.
