### ISSUE TITLE
Pass compiler options?

### ISSUE THREAD

**Issue by pvelesko** [shenxianpeng/cpp-linter-action#34]
Is there a way to pass compiler options? The things that come after the double dash:

```
clang-tidy ./file.cpp --checks=* -- -I/home/include/path
```

**Comment by 2bndy5** [comment]
No, we let clang-tidy rely on a compiler database file. The demo directory uses a generic .txt file form of this as you can observe https://github.com/shenxianpeng/cpp-linter-action/blob/master/demo/compile_flags.txt

**Comment by pvelesko** [comment]
Just realized that I don't have to keep updating my database file on every push so it's fine as it stands
