### ISSUE TITLE
add user input option for compilation database

### ISSUE THREAD

**Issue by 2bndy5** [shenxianpeng/cpp-linter-action#41]
I took a peek at the public forks for this repo, and I found an interesting idea implemented by @DingXuefeng about specifying a path for clang-tidy to use when looking for the compilation database file.

This contribution would mean cherry picking a couple commits from [@DingXuefeng's fork](https://github.com/DingXuefeng/cpp-linter-action/commits/master), namely https://github.com/DingXuefeng/cpp-linter-action/commit/d54440f98b8935f36b61f4bd9acf982806370b57 & https://github.com/DingXuefeng/cpp-linter-action/commit/5891ebac7db574caac402a086d1d71e9e17f4ea2

I should note that the [bugfix commit](https://github.com/DingXuefeng/cpp-linter-action/commit/68265e9e98cebca9e4e164826c14918ad3a01f1f) is already part of the changes in #40 

Any objections?

**Comment by shenxianpeng** [comment]
Nope. I also think it's good to have this improvement.

**Comment by 2bndy5** [comment]
Great! I will see what I can do about preserving @DingXuefeng authorship.

**Comment by shenxianpeng** [comment]
cherry-pick from different repos could also preserve the authorship

**Comment by 2bndy5** [comment]
That's what I'm hoping. I also hope to get a confirmation from @DingXuefeng, but I don't think it is necessary.

**Comment by shenxianpeng** [comment]
Yes, it's great to get confirmation from @DingXuefeng. 
I have tried to cherry-picked the branch compilation-database which has author information but also mine.

**Comment by DingXuefeng** [comment]
Hi, just see the message. I am glad to share it. I created a PR, which I think would be the easiest solution.
