### ISSUE TITLE
Add an example as a python package for general CI tools

### ISSUE THREAD

**Issue by shenxianpeng** [shenxianpeng/cpp-linter-action#52]
Hi @2bndy5 the following example you mentioned in the discussions yesterday is very instructive.

Someone who uses other CI tools like Travis CI, CircleCI, Jenkins, etc instead of GitHub Actions can also use this repo code if their code is hosted on GitHub. 

I'm thinking whether updating this example code to README may help.

```bash
# Requires clang-format, clang-tidy installed

# Install linter package
python3 -m pip install git+https://github.com/shenxianpeng/cpp-linter-action

# Generate compilation database  
mkdir build && cmake -Bbuild src -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

# Run linter as a package
# --version arg is useless on Windows - it will use whatever version is installed
# --ignore the build/* artifacts generated by CMake
# --database indicates the path of the generated database
python3 -m cpp_linter.run --ignore=build --database=build --thread-comments=true

# Fail fast?!
if [ $? -ne 0 ]; then
    echo "Some files failed the linting checks!"
fi
```

**Comment by 2bndy5** [comment]
Funny you opened this just now. I'm in the process of opening a PR to merge the needed modifications for windows-based runners. I'm literally in the process of updating the README for Windows-based runners.

As for using this code on other CI services (non-github), I think a fork of this repo is currently required since this action's src code heavily relies on github-specific env vars. While similar env vars might be available on other CI services, they might be named differently (which is a breaking point).

It would take a lot more research and testing to adapt the source code for other CI services' env vars, but it is definitely possible. I don't have a bitbucket account, but I do have a gitlab account (never really used though) and a travisCI account (haven't used it in years though).

**Comment by shenxianpeng** [comment]
OK, this needs much effort. I just realized if their code is hosted on GitHub why not use GitHub Actions :zany_face:

**Comment by 2bndy5** [comment]
It is a good idea though. I didn't think to use it for other CI services like this. Additionally, this is starting to address one of your original design goals: Make it compatible with bitbucket pipelines.

Now that we can take advantage of python, I think this idea is better than maintaining a different fork for each CI service.

**Comment by 2bndy5** [comment]
> Then the current source code folder cpp_linter can be moved from shenxianpeng/cpp-linter-action to cpp-linter/cpp-linter. then this cpp-linter-action can install linter python package with `python3 -m pip install git+https://github.com/cpp-linter/cpp-linter`

I can tell you from experience that transferring the repo from one account to another will not screw up existing workflows that still use the old account. Github does some clever redirecting in the event of repo transfers, although that might be limited to a year or so.

**Comment by shenxianpeng** [comment]
So you prefer to transfer to cpp-linter org? 

If we transferred, I can also do the following steps to minimize the impact 

1. use my account to fork `cpp-linter/cpp-linter-action`
2. update the child repo README deprecated, add a link to the parent repo
3. then make the child repo `shenxianpeng/cpp-linter-action` as archived

**Comment by 2bndy5** [comment]
If you want to transfer the repo, then wait till the PRs are closed or merged because I've heard horror stories about transferring repos with open PRs.

**Comment by shenxianpeng** [comment]
OK, let's wait until PRs are merged.

**Comment by 2bndy5** [comment]
> 1. use my account to fork `cpp-linter/cpp-linter-action`
> 
> 2. update the child repo README deprecated, add a link to the parent repo
> 
> 3. then make the child repo `shenxianpeng/cpp-linter-action` as archived

I think making this repo into an archived fork of the transferred repo is a bad idea. It might confuse github into disabling the auto-redirect behavior. Not to mention confusing people about which action code is actually being used (archived or not).

**Comment by 2bndy5** [comment]
Technically, you could also transfer the docker image repo to the @cpp-linter org as well. I'm not sure if that would have implications on dockerhub though.

**Comment by shenxianpeng** [comment]
Thank you for your suggestions. I'm going to transfer, and it seems need necessary changes after transfered

**Comment by shenxianpeng** [comment]
I created a branch named [transfer-update](https://github.com/cpp-linter/cpp-linter-action/tree/transfer-update) for transfer ownership update.
