### ISSUE TITLE
wish clang-format comments could be a macro instead of comment?

### ISSUE THREAD

**Issue by shenxianpeng** [shenxianpeng/cpp-linter-action#54]
I noticed the user mentioned [here](https://github.com/google/flatbuffers/pull/7252/files#r851705769)

> I formatted the whole file, and these were wrong.
> I really wish clang-format comments could be a macro instead of comment.

I'm not quite sure what he needs, @2bndy5 do you have any idea?

**Comment by 2bndy5** [comment]
That comment is specific to controlling clang-format in a source file. Specifically, he wants to use a preprocessor mechanism instead of a source code comment. I don't think there's anything we can do to help.

**Comment by shenxianpeng** [comment]
I see, there is nothing we can do, thank you!
