### ISSUE TITLE
Prevent action downloading files after GH checkout action

### ISSUE THREAD

**Issue by 2bndy5** [shenxianpeng/cpp-linter-action#6]
If you require the user's repos uses GH's actions/checkout prior to the cpp-lint action, then all files are already there in a folder designated by the environment variable `$GITHUB_WORKSPACE`.

The JSON that the bash script is getting the list of download URLs can instead be used to get the relative path of files. This way, you'd only have to prefix the filenames with `$GITHUB_WORKSPACE` when passing them to clang-* tools.

**Comment by 2bndy5** [comment]
I'm also exploring the possibility of using [GH CLI](https://cli.github.com/) (which is available to all GH runners) instead of the json option. That would mean less dependencies to install in this action's Dockerfile. Maybe this will be a seperate issue when I understand it better.

As for installing clang-* in this action's Dockerfile, you could switch to a docker container that already has them installed... again that would be yet another issue.

**Comment by shenxianpeng** [comment]
In my daily work, I used Bitubkcet, I want to bring this linter action to Bitbucket, using shell script may be easier to integrate with my internal environment as I don't need to install GH CLI. 

But here in GitHub, using the environment variable `$GITHUB_WORKSPACE` and GH CLI is a great idea.

Btw, there is a docker image [clang-tool](https://github.com/shenxianpeng/clang-tool) I created several days ago include clang-format and clang-tidy maybe useful.

**Comment by 2bndy5** [comment]
>In my daily work, I used Bitubkcet, I want to bring this linter action to Bitbucket, using shell script may be easier to integrate with my internal environment as I don't need to install GH CLI

Interesting! I initially wanted to get involved as a way to learn bash scripting better. I'm now learning more about the git's REST API (which is what the JSON comes from). Maybe we can check for the file's existence before downloading it. I have another idea of letting clang-tidy look for a custom defined .clang-tidy file instead of hard-coded checks. However, the entire repo needs to be present for clang-tidy to find a clang-tidy config file (and a _compile_commands.json_ referred to as "compilation database" in clang-tidy's output).

>Btw, there is a docker image clang-tool I created several days ago include clang-format and clang-tidy maybe useful.

Cool! Could it be tailored to have all available versions of clang-*? That way we can let users specify what version (via another new input  arg) to use; this is a common input option for most other clang-tidy actions.
```
brendan@B-DESKTOP:/mnt/c/Users/ytreh/Documents/GitHub/cpp-linter-action$ apt list clang-tidy-*
Listing... Done
clang-tidy-10/focal,now 1:10.0.0-4ubuntu1 amd64 [installed,automatic]
clang-tidy-11/focal-updates 1:11.0.0-2~ubuntu20.04.1 amd64
clang-tidy-12/focal-updates 1:12.0.0-3ubuntu1~20.04.3 amd64
clang-tidy-6.0/focal 1:6.0.1-14 amd64
clang-tidy-7/focal 1:7.0.1-12 amd64
clang-tidy-8/focal 1:8.0.1-9 amd64
clang-tidy-9/focal 1:9.0.1-12 amd64
```

```
brendan@B-DESKTOP:/mnt/c/Users/ytreh/Documents/GitHub/cpp-linter-action$ apt list clang-format-*
Listing... Done
clang-format-10/focal 1:10.0.0-4ubuntu1 amd64
clang-format-11/focal-updates 1:11.0.0-2~ubuntu20.04.1 amd64
clang-format-12/focal-updates 1:12.0.0-3ubuntu1~20.04.3 amd64
clang-format-6.0/focal 1:6.0.1-14 amd64
clang-format-7/focal 1:7.0.1-12 amd64
clang-format-8/focal 1:8.0.1-9 amd64
clang-format-9/focal 1:9.0.1-12 amd64
```

as you can see, the versions available are aligned.

**Comment by 2bndy5** [comment]
@shenxianpeng I switched to your docker image and runtime has decreased by 30+ seconds!!!

**Comment by shenxianpeng** [comment]
> @shenxianpeng I switched to your docker image and runtime has decreased by 30+ seconds!!!

Wow, this is great! I think it can have all available versions of clang-*. I'm just not so familiar with clang-*, from your experience, will users care about the version?

Support custom defines .clang-tidy file makes a lot of sense to users.

**Comment by 2bndy5** [comment]
Judging from the differences in the clang docs, compatibility between versions of clang are sketchy. From my experience, its better to have the action run with the same version of clang that you're using locally. Linux `apt` will default to installing v10, but latest stable release is v12 on GH (which is where I get the clang installer for Windows). Yes, I think people will care.

**Comment by shenxianpeng** [comment]
Because clang-tool image includes clang-format and clang-tidy, so I guess rename the docker image from `xianpengshen/clang-tool` to `xianpengshen/clang-tools` may be more suitable. I'll do this change later.

**Comment by 2bndy5** [comment]
@shenxianpeng I can't dynamically use tags in the Dockerfile's `FROM` option. So, specifying a version has to come at runtime. Meaning all versions of available clang-tools need to be installed in 1 image. Then I can execute the user-specified version like
```bash
clang-tidy-"$CLANG_VERSION" ... $SOURCE_FILE
```

**Comment by 2bndy5** [comment]
While looking into solving #8 , I've also added this feature in the process. I'll wait till #10 is merged to rebase then open another PR...

Note I haven't started using GH CLI at all; I'm purely using GH's REST API only (hopefully that's still somewhat compatible with [a REST API from Bitbucket](https://developer.atlassian.com/server/bitbucket/reference/rest-api/)).
