### ISSUE TITLE
add compatibility for push events

### ISSUE THREAD

**Issue by 2bndy5** [shenxianpeng/cpp-linter-action#8]
It would be more useful if a user is notified by this action (before opening a PR) that a file from a commit needs formatting. Users workflows can clarify what [events to trigger on](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#on).

**Comment by shenxianpeng** [comment]
We could suggest that the user open the `push` event in the README.md file

**Comment by 2bndy5** [comment]
properly addressing this issue means changing and adjusting the `jq` args

https://github.com/shenxianpeng/cpp-linter-action/blob/180d0c2ee05e2fb21f3f237078471c130344c46f/runchecks.sh#L12

https://github.com/shenxianpeng/cpp-linter-action/blob/180d0c2ee05e2fb21f3f237078471c130344c46f/runchecks.sh#L15-L16

**Comment by shenxianpeng** [comment]
Agree with you.
